Music/urls.py
from django.conf.urls import url
from . import views

app_name = 'Music'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^albums/add/$', views.AlbumsCreate.as_view(), name='album-create'),
    url(r'^albums/addsongs/$', views.SongsCreate.as_view(), name='song-create'),

    url(r'albums/song/(?P<pk>[0-9]+)/$', views.SongsDetail.as_view(), name='song-detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    url(r'albums/song/(?P<pk>[0-9]+)/delete/$', views.SongsDelete.as_view(), name='song-delete'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.AlbumsDelete.as_view(), name='album-delete'),

    url(r'^(?P<pk>[0-9]+)/update/$', views.AlbumsUpdate.as_view(), name='album-update'),
    url(r'albums/song/(?P<pk>[0-9]+)/update/$', views.SongsUpdate.as_view(), name='song-update'),

    url(r'^register/$', views.UserFormView.as_view(), name='register')
]

Viberr/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('Music.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Music/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Albums(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=250)
    album_logo = models.FileField()

    #This method is called whenever the user adds or updates the entry
	#i.e this is used for redirecting user to a different a page
    def get_absolute_url(self):
        return reverse('Music:detail', kwargs={'pk':self. pk})

    def __str__(self):
        return 'Album : '+str(self.album_title)+' - Artist : '+str(self.artist)


class Songs(models.Model):
    album = models.ForeignKey(Albums, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=25)
    song_title = models.CharField(max_length=250)

    def __str__(self):
        return 'Song title : '+str(self.song_title)

    def get_absolute_url(self):
        return reverse('Music:detail', kwargs={'pk':self.album.pk})

Music/forms.py
# The user model is being imported to tweak it
# as we dont want it be as default that is provided by django
from django.contrib.auth.models import User
from django import forms

# Inherited the base form class
class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

Music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Albums, Songs
from django.core.urlresolvers import reverse_lazy, reverse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import UserForm
from django.views.generic import View

class IndexView(generic.ListView):
    template_name = 'Music/index.html'
    # this query set will be stored in a variable
    # simialar to the model name but in lowercase
    context_object_name = 'albums'
    def get_queryset(self):
        return Albums.objects.all()


class DetailView(generic.DetailView):
    model = Albums
    template_name = 'Music/detail.html'


class AlbumsCreate(CreateView):
    model = Albums
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class SongsCreate(CreateView):
    model = Songs
    fields = ['album', 'file_type', 'song_title']


class SongsDetail(generic.DetailView):
    model = Songs
    template_name = 'Music/songs_detail.html'


class AlbumsDelete(DeleteView):
    model = Albums
    success_url = reverse_lazy('Music:index')


class SongsDelete(DeleteView):
    model = Songs
    success_url = reverse_lazy('Music:index')


class AlbumsUpdate(UpdateView):
    model = Albums
    fields = ['artist', 'album_title', 'genre', 'album_logo']
    template_name = 'Music/albums_form.html'


class SongsUpdate(UpdateView):
    model = Songs
    fields = ['album', 'file_type', 'song_title']
    template_name = 'Music/songs_form.html'


# as we are making neither a detail view or list view
# we are inheriting a generic view

class UserFormView(View):
    form_class = UserForm # this variable will contain the basic form skeleton
    # i.e the how the input fields will be there
    template_name = 'Music/registration-form.html'

    # Whenever the form is to be shown to the user
    # empty  file- this method will be called
    def get(self, request):
        form = self.form_class(None)# this is set to None so that we give the user an empty form
        return render(request,self.template_name, {'form': form})# this will give the user an empty form

    # take the data and process it
    def post(self, request):
        # this will take the data from the form
        form = self.form_class(request.POST)
        # Check whether the form is valid

        if form.is_valid():
            user = form.save(commit=False)
            # get the clean username and password
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            user.set_password(password)
            user.save()

            user = (authenticate(username=username, password=password))

            #return redirect(reverse('Music:index'))
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('Music:index')

        return render(request, self.template_name, {'form': form})

Music/templates/Music/album-create.html
{% extends 'Music/navbar.html' %}

{% block title %}
Create an Album.
{% endblock %}

Music/templates/Music/album_form.html
{% extends 'Music/navbar.html' %}

{% block title %}
Create Album
{% endblock%}

Music/templates/Music/albums_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

Music/templates/Music/albums_form.html
{% extends 'Music/navbar.html' %}

{% block title %}
Album
{% endblock%}

{% block body%}
<h1>Album Create form</h1>
<!--Form control-->
<!--Enctype must be specified or else images wont be accepted-->
<form action="" method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    <div class="input-group" >
        {% include 'Music/form-template.html'%}
    </div>
    <div class="input-group btn">
        <button class="btn btn-success" type="submit">Add</button>
    </div>
</form>


{% endblock %}

Music/templates/Music/detail.html
{% extends 'Music/navbar.html'%}
{% block title %}
{{ pk.album_title }}
{% endblock %}

<!--The result is stored in iterable named a/c to the model name-->
{% block body %}
<div class="jumbotron" align="center">
<img src="{{albums.album_logo.url}}" alt="album logo goes here"
     class="img-responsive" width="150" height="200">
<h2>Album Title : {{ albums.album_title }}</h2>
<h3>Artist name : {{ albums.artist }}</h3>

<a href="{% url 'Music:album-update' albums.pk %}"><button class="btn btn-primary">
        <span class="glyphicon glyphicon-plus"></span>&nbspUpdate Album
</button></a>

<h3>Songs : </h3>

<ul>
    {% for song in albums.songs_set.all %}
    <a href="{% url 'Music:song-detail' song.pk %}"><li>{{song.song_title}}</li></a>
    {%endfor%}
    <br>
    <a href="{% url 'Music:album-delete' albums.pk %}"><button class="btn btn-danger">
        <span class="glyphicon glyphicon-trash"></span>
    </button></a>&nbsp&nbsp
    <a href="{% url 'Music:song-create'%}"><button class="btn btn-primary">
        <span class="glyphicon glyphicon-plus"></span>&nbspAdd a new Song
    </button></a>
</ul>
</div>
{% endblock %}

Music/templates/Music/form-template.html
{% for field in form %}
<style>
    .input-group{
        padding:50x;
    }
</style>
    <div class="input-group">
        <label>
            {{ field.label_tag }}
        </label>
        <div >{{field}}</div>

    </div>
{% endfor %}

Music/templates/Music/index.html
{% extends 'Music/navbar.html' %}

{% block title %}
Albums
{% endblock %}

{% block body %}
<h1>This is a list of all albums.</h1>

<a href="{% url 'Music:album-create' %}">
    <button class="btn btn-primary">
        <span class="glyphicon glyphicon-plus"></span>&nbspAdd an Album
    </button>
</a>
<br>
<br>
{% for album in albums %}
<div class="container">
    <div class="row">
        <!---Will contain the image of the album-->
        <div class="col-sm-4">
            <img src="{{album.album_logo.url}}" class="img-responsive" style="padding:10px;margin:10px;">
        </div>
        <!--Will display the contents of the album and contain a link to the detail-->
        <div clas="col-sm-8" >
            <div class="row">
                <div class="col-sm-6">
                    <h3>Album details</h3>
                    <h4><strong>Artist Name : </strong>
                        {{album.artist}}
                    </h4>
                    <h4><strong>Genre : </strong>
                        {{album.genre}}
                    </h4>
                </div>
                <div class="col-sm-6">
                    <a href="{% url 'Music:detail' album.id %}">
                        <button class="btn btn-info">
                            <span class="glyphicon glyphicon-icon-sign"></span>&nbspView Details
                        </button>
                    </a>
                </div>
            </div>

        </div>
    </div>
    <br>
</div>
{% endfor %}

{% endblock %}

Music/templates/Music/navbar.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <link rel="shortcut icon" href="http://www.iconarchive.com/download/i106183/papirus-team/papirus-apps/preferences-desktop-keyboard-shortcuts.ico">
        <title>{% block title%}Website{% endblock %}</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'Music/style.css'%}">
        <style>
            a{
                text-decoration:none;
            }
        </style>
    </head>

    <body>
    <!--Navigation bar-->
        <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!--Navigation bar header-->
            <div class="navbar-header">
                <div >
                    <a href="{% url 'Music:index' %}" class="navbar-brand">Website title goes here</a>
                </div>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!--Navigation bar header ends-->

            <!--Menu items-->
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'Music:index' %}">Albums&nbsp
                        <span class="glyphicon glyphicon-cd" ></span>
                    </a></li>
                    <li><a href="#">Music&nbsp
                        <span class="glyphicon glyphicon-music"></span>
                    </a></li>
                </ul>
            <!--Menu items-->

            <!--Menu Items to the right-->
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Logout&nbsp
                        <span class="glyphicon glyphicon-off"></span>
                    </a></li>
                </ul>
            <!--Menu Items to the right-->

                <!--Search Form-->
                <form action="#" role="search" method="post" class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" name="q" class="form-control" placeholder="Search">
                    </div>
                    <input type="submit" value="Search" name="q" class="btn btn-default">
                </form>
            </div>

        </div>
    </nav>
    <!--Navigation bar ends here-->
    </body>
{% block body %}
{% endblock %}
</html>

Music/templates/Music/registration-form.html
{% extends 'Music/navbar.html' %}

{% block title %}
Register
{% endblock %}

{% block body %}
<form action="" method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    <div class="input-group" >
        {% include 'Music/form-template.html'%}
    </div>
    <div class="input-group btn">
        <button class="btn btn-success" type="submit">Register</button>
    </div>
</form>
{%endblock%}

Music/templates/Music/songs_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm"/>
</form>

Music/templates/Music/songs_detail.html
{% extends 'Music/navbar.html' %}

<!--The primary related details are stored in variable name
similar to the model i.e songs-->
{% block title %}
Details for {{songs.song_title}}
{% endblock %}

{% block body %}
<div class="jumbotron text-center">
<h2>{{ songs.song_title }}</h2>

<h3><strong>Song album : </strong>{{songs.album}}</h3>
<h3><strong>Song format : </strong>{{songs.file_type}}</h3>
<a href="{% url 'Music:song-delete' songs.pk %}">
    <button class="btn btn-danger">
    <span class="glyphicon glyphicon-trash"></span></button>
</a>

<a href="{% url 'Music:song-update' songs.pk %}">
    <button class="btn btn-primary">
    <span class="glyphicon glyphicon-plus"></span>&nbspUpdate Song</button>
</a>
    </div>
{% endblock %}

Music/templates/Music/songs_form.html
{% extends 'Music/navbar.html' %}

{% block title %}
Add a Song
{% endblock%}

{% block body%}
<h1>Song Create form</h1>
<!--Form control-->
<form action="" method="POST">
    {%csrf_token%}
    <div class="input-group" >
        {% include 'Music/form-template.html'%}
    </div>
    <div class="input-group btn">
        <button class="btn btn-success" type="submit">Add</button>
    </div>
</form>


{% endblock %}